name: hello-world
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  issue_validate:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: echo "${{ steps.parse.outputs.data }}"
      - name: Create Pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update issue forms"
          title: "Update issue forms"
          body: "${{ steps.parse.outputs.data }}"
          branch: "update-issue-forms"
          labels: "update-issue-forms"
          reviewers: "priyanka-thapa-alight"
          assignees: "priyanka-thapa-alight"
          token: ${{ secrets.GITHUB_TOKEN }}
